"""empty message

Revision ID: 075de170caa0
Revises: 087173304240
Create Date: 2020-03-15 15:30:27.553968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075de170caa0'
down_revision = '087173304240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_id', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'google_id')
    # ### end Alembic commands ###
