"""empty message

Revision ID: 656183e478e1
Revises: 7e98fd113ced
Create Date: 2020-02-09 21:51:05.203937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656183e478e1'
down_revision = '7e98fd113ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardcopies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['controller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=True),
    sa.Column('made_at', sa.DateTime(), nullable=True),
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.Column('hardcopy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardcopy_id'], ['hardcopies.id'], ),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('hardcopies')
    # ### end Alembic commands ###
